name = "SpiderMan"
uuid = "8b3c21a4-0b6b-4c74-bcc4-679d0c8105ea"

[deps]
Aeron = "42ac8a32-990f-4d8c-aece-52d731103226"
Alert = "28312eec-4d86-447d-83ad-bc2b262de792"
AstroImages = "fe3fc30c-9b16-11e9-1c73-17dabf39f4ad"
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
CImGuiPack_jll = "333409e9-af72-5310-9767-d6ad21a76a05"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImGuiGLFWBackend = "623d79b3-9695-4e60-bd7e-2a5aabaa6933"
ImGuiOpenGLBackend = "9d0819b4-44e7-43a2-ad03-8fb999128168"
ImPlot = "e8efc688-5342-4ad4-b4ba-9025a731b363"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LibCImGui = "9be01004-c4f5-478b-abeb-cb32b114cf5e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
